project 'DesignCodeAppLessons.xcodeproj'
# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'DesignCodeAppLessons' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DesignCodeAppLessons
  pod 'Spring'
  pod 'TPKeyboardAvoiding'
  pod 'MKRingProgressView'
  pod 'Ambience'
  pod 'RealmSwift'
  pod 'Kingfisher', '~> 4.6'

end
